In [3]:
# numpy demo
import numpy as np

# 1-D Array
my_list = [1, 2, 3]
x = np.array(my_list)
x

array([1, 2, 3])

In [4]:
# 2-D Array
m = np.array([[7, 8, 9],
              [1, 2, 3]])
m

array([[7, 8, 9],
       [1, 2, 3]])

In [5]:
# dimension of the array
m.shape

(2L, 3L)

In [7]:
# function arange
rng_array = np.arange(0, 11, 2)
rng_array

array([ 0,  2,  4,  6,  8, 10])

In [8]:
# function reshape
rng_array.reshape(2, 3)

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [10]:
# not inplace shaping
rng_array

array([ 0,  2,  4,  6,  8, 10])

In [12]:
# function linspace
lns_array = np.linspace(0, 4, 9)
lns_array

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [14]:
# changing shape of array inplace
lns_array.resize(3, 3)
lns_array

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [15]:
# matrix creation methods
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
# identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
# creating diagonal arrays
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [19]:
# creating array with repeating list
np.array([1, 2, 3] * 4)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [20]:
np.repeat([1, 2, 3], 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [21]:
# combining arrays
p = np.ones((3, 3))
p

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
# vertical merging
np.vstack([p, 3 * p])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [23]:
np.hstack([p, 2 * p])

array([[1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 2., 2., 2.]])

In [24]:
# operations
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
x + y

array([5, 7, 9])

In [25]:
x - y

array([-3, -3, -3])

In [26]:
x * y

array([ 4, 10, 18])

In [27]:
x / y

array([0, 0, 0])

In [28]:
y / x

array([4, 2, 2])

In [29]:
x ** y

array([  1,  32, 729])

In [30]:
x.dot(y)

32

In [31]:
z = np.vstack([x, y])
z

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
z.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [33]:
# checking datatype of x elements
x.dtype

dtype('int32')

In [34]:
# changing data type of x
x.astype('f')

array([1., 2., 3.], dtype=float32)

In [35]:
# math functions
a = np.array([-4, -1, 1, 4, 5])
a

array([-4, -1,  1,  4,  5])

In [36]:
a.sum()

5

In [37]:
a.min()

-4

In [38]:
a.std()

3.286335345030997

In [39]:
a.mean()

1.0

In [40]:
a.max()

5

In [41]:
# getting index of maximum and minimum values in the array
a.argmax()

4

In [42]:
a.argmin()

0

In [43]:
# indexing/slicing operations on array
s = np.arange(13) ** 2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [44]:
s[0]

0

In [45]:
s[-1]

144

In [61]:
s[-2:]

array([121, 144])

In [62]:
s[-4::2]

array([ 81, 121])

In [46]:
# indexing/slicing on multi D arrays
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [64]:
r[2, 2]

14

In [65]:
r[3, 3:6]

array([21, 22, 23])

In [66]:
r[5, ::2]

array([30, 32, 34])

In [67]:
# conditional hashing
r[r > 30]

array([31, 32, 33, 34, 35])

In [68]:
r[r > 15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35])

In [71]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [47]:
# copying data
r2 = r[:3, :3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [48]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [49]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [50]:
# IMP - r also gets modified - to avoid it we will use .copy() method

In [51]:
test = np.random.randint(0, 10, (4, 3))
test

array([[6, 3, 8],
       [2, 4, 2],
       [0, 6, 0],
       [2, 3, 0]])

In [52]:
# iterating on rows
for row in test:
    print row

[6 3 8]
[2 4 2]
[0 6 0]
[2 3 0]


In [53]:
# iterating by index
for i in range(len(test)):
    print test[i]

[6 3 8]
[2 4 2]
[0 6 0]
[2 3 0]


In [82]:
# interate by index, row
for i, row in enumerate(test):
    print 'row: ', i, ' is ', row

row:  0  is  [8 4 6]
row:  1  is  [7 0 9]
row:  2  is  [1 5 0]
row:  3  is  [1 8 6]


In [83]:
# to itereate over multiple iterables
test2 = test ** 2
test2

array([[64, 16, 36],
       [49,  0, 81],
       [ 1, 25,  0],
       [ 1, 64, 36]])

In [84]:
for i, j in zip(test, test2):
    print i, ' + ', j, ' = ', i + j

[8 4 6]  +  [64 16 36]  =  [72 20 42]
[7 0 9]  +  [49  0 81]  =  [56  0 90]
[1 5 0]  +  [ 1 25  0]  =  [ 2 30  0]
[1 8 6]  +  [ 1 64 36]  =  [ 2 72 42]
